<?php
/**
 * @var M2task\BannerManagement\Block\Widget\Banners $block
 */
?>

<?php if ($block->getRandomBanner()) : ?>
<div class="banner-wrapper">
    <div class="banner-content">

    </div>
    <div class="banner-modal">
        <div class="banner-modal-popup">
            <div class="banner-modal-popup_content">
                <?= $block->getBannerData('banner_popup_text_content') ?>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "banner":{
            "desktop_image": "<?= $block->getMediaUrl() . $block->getBannerData('desktop_image') ?>",
            "mobile_image": "<?= $block->getMediaUrl() . $block->getBannerData('mobile_image') ?>"
        }
    }
}
</script>

<?php else: ?>
<div class="banner-error">
    Banner group <?= $block->getData('banner_group_code') ?> not found
</div>
<?php endif; ?>



