<?php
/**
 * @var M2task\BannerManagement\Block\Widget\Banners $block
 */
?>

<div class="banner-wrapper">
    <picture class="banner-background">
        <source media="(min-width: 768px)" srcset=""/>
        <img src="" alt="Banner" />
    </picture>
    <div class="banner-content">

    </div>
    <div class="banner-modal">
        <div class="banner-modal-popup">
            <div class="banner-modal-popup_content">

            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "banner":{
            "groupCode":"<?= $block->getGroupCode() ?>",
            "baseUrl":"<?= $block->getUrl('graphql/') ?>"
        }
    }
}
</script>




