<?php
/**
* Copyright © Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/

/* @var $block \M2task\BannerManagement\Block\Widget\NewBanners */

?>

<div class="maincontent">
    <div class="title">
        <span class="widget-title"><?php echo __("RH Widget Title : "); ?></span>
        <span class="widget-title-val"><?php echo $block->getData('rh_title'); ?></span>
    </div>
    <div class="description">
        <span class="widget-desc"><?php echo __("RH Widget Description : "); ?></span>
        <span class="widget-desc-val"><?php echo $block->getData('rh_description'); ?></span>
    </div>
</div>
